### ISSUE TITLE
npm run dev gives vitejs warning

### ISSUE THREAD

**Issue by alarbada** [solidjs/templates#146]
The template is for `ts-tailwindcss`

```bash
The CJS build of Vite's Node API is deprecated. See https://vitejs.dev/guide/troubleshooting.html#vite-cjs-node-api-deprecated for more details.
```

**Comment by Mathnerd314** [comment]
I got it for the `js` template too. Fix is to add `"type": "module",` to `package.json`.

**Comment by dragove** [comment]
mv `vite.config.js` or `vite.config.ts` to `vite.config.mjs` or `vite.config.mts`
