### ISSUE TITLE
Tailwind CSS template

### ISSUE THREAD

**Issue by arnaugomez** [solidjs/templates#18]
Can I make a template with the tailwind css setup?

**Comment by dharmaturtle** [comment]
Alexandre beat you to it lol: https://github.com/solidjs/templates/commit/5ecf3a157ae40fd7e8a2121ce32284ad772df237

**Comment by amoutonbrady** [comment]
Sorry, it seems like I didn't see your issue...
You can add a a tailwind + js template if you would like :)
