### ISSUE TITLE
Format the files using Prettier

### ISSUE THREAD

**Issue by aminya** [solidjs/templates#21]
It would be nice to format all the files with Prettier. For example, semicolons are optional, while this starter template uses them. 
Prettier does not need to be used in the actual template though.

**Comment by amoutonbrady** [comment]
That's a good idea. I'll see how I can implement that in a pnpm monorepo :)

**Comment by amoutonbrady** [comment]
Added a basic prettier and ran it across the whole project. Feel free to let me know if the rules feels "general purpose" enough to you :)
