### ISSUE TITLE
provide a start script

### ISSUE THREAD

**Issue by danielo515** [solidjs/templates#31]
Hello. I think this initiative is great! Thanks for it.
However, something that I find weird is that you don't have a start script on the templates.
For me is already an standard to do `yarn && yarn start` on any TS or JS project, without even having to look at the package.json.

Any reason you decided to deviate from this?
Regards!

**Comment by amoutonbrady** [comment]
Hey! Most project use `dev` as the dev command and `build` as the build command.
`start` is usually used as a starting the production app, which in our case, well there's nothing to start haha
We could however use the `vite serve` as start. I'll think about it!
When `solid-start` is ready, the `start` script will make a lot more sense.

**Comment by danielo515** [comment]
I think it is depending on which kind of projects you usually work in. Sure start is used for production apps, but that is usually backend side. For front-end apps,where the product is delivered with build then upload the artifacts the start has usually nothing to do with the final APP. That's why I was proposing to take advantage of the usual start script to "start working" on the project. IMO start can be contextual to each project
