### ISSUE TITLE
Recieving error on running degit: ! zlib: unexpected end of file

### ISSUE THREAD

**Issue by cognociente** [solidjs/templates#37]
I can't succesfullly execute `npx degit`
Running Ubuntu in WSL2 on Windows 11.

Get the following error:
! zlib: unexpected end of file

And just an empty directory is created

**Comment by cognociente** [comment]
Running the following seemed to work but I have no idea why: 
rm -rf ~/.degit/github/solidjs

**Comment by BlackyWolf** [comment]
Likewise. I ended up having to delete `C:\Users\<user>\.degit` after which it worked.

**Comment by amoutonbrady** [comment]
That's odd. Probably an issue with degit more so than Solid or starters themselves :(
