### ISSUE TITLE
Name import in vitest tests to be { test as it }

### ISSUE THREAD

**Issue by chris-czopp** [solidjs/templates#64]
Could we change this: 

```ts
import { describe, expect, test } from 'vitest';
```
to this:

```ts
import { describe, expect, test as it } from 'vitest';
```

and then we could do `it('should do stuff'...)`

https://github.com/solidjs/templates/blob/master/ts-vitest/src/todo-list.test.tsx#L1

**Comment by amoutonbrady** [comment]
Hey, thanks for your proposal :)

Fortunately this something you could do on your own after cloning the template.
Since the main goal of these templates is to be as generic as possible, I'd argue to not add that.
