### ISSUE TITLE
Typescript template not working

### ISSUE THREAD

**Issue by zanzlender** [solidjs/templates#96]
Hello, I've just tried using `npx degit solidjs/templates/ts my-solid-project` to setup my new SolidJS project, but when I try to run it I get a `! zlib: unexpected end of file` error.

**Comment by amoutonbrady** [comment]
I updated all the dependencies of the repo. Do you still have the issue?

I ran into a similar tool by the nuxt team, could you try `npx gitget solidjs/templates/ts my-solid-project`?

Thanks!
