### ISSUE TITLE
README / script errors with some templates

### ISSUE THREAD

**Issue by LadyBluenotes** [solidjs/templates#99]
Currently, there are some READMEs that say you can run a `npm start` script to get the template up and running, but it is throwing an error saying that script is not available. For the sake of consistency among all templates, it may be worth either removing `npm start` from the few who have it, or adding it to the templates below.

The templates I've encountered with this are:
- ts-minimal
- ts-unocss
- ts-windicss
- ts-router
- ts-bootstrap
- ts-tailwindcss
- ts-sass

**Comment by amoutonbrady** [comment]
I merged the PR thank you both!
